### PR TITLE
Refactor the pattern matching code

### LINKED ISSUE #68: Default binding syntax: a path to optional fields
My team often comes across the scenario where we receive an event, or even a fact to pattern match against, that has optional, `omitempty` fields.  In these cases, we are forced to bind the parent map and dive into it in a javascript code block.  This often becomes very cumbersome and greatly increases the rule configuration complexity.

We would like to propose a syntax for bindings in patterns for specifying default values to fall back to in the event that the field is missing, and we seek feedback from @jsccast.  This is work that we can carry out, provided that you agree with this kind of approach, and you do not see a major technical barrier to implementing this.

## Default binding syntax
The idea here is to introduce another special character that signals the start of a default JSON value: `|`.

example:
```json
{
    "pattern": {
        "data": {
            "code": "?code|\"ABC\"",
            "amount": "?amount|0"
        }
    }
}
```
In the above example, if `code` is omitted, the binding will be a string with the value "ABC".  If `amount` is omitted, the binding will be a number with the value `0`.

## Default value propagation
Additionally, we propose that if `data` is omitted in example 2, the pattern will still match with the default bindings for `code` and `amount`, since they both have defaults.  If either `code` or `amount` did not have a default, then a missing `data` field would result in no match.

### PR DESCRIPTION
**Pull request by decibelcooper**
Closes #68 

This PR puts the pattern matching code behind an interface.  The user now has the ability to provide their own pattern matcher.  It also pulls in `github.com/Comcast/sheens/match` to implement the default pattern matcher.

To review, I recommend ignoring the diff of `core/match.go`, and just looking at the new version of it in its entirety to see the direction I went there.  The idea I was going with, BTW, was to maintain backwards compatibility.  Perhaps Rulio can start seeing some release tags, and then when it is ready for a breaking change, we can clean this up.

### CODE REVIEW

**Comment by decibelcooper** [comment]
@jsscast this is ready for review.  LMK if you'd like to see any changes or a different direction.

**Comment by jsccast** [comment]
Sorry, I missed this notification. I'll take a look ASAP.

**Review by jsccast — APPROVED** [review]
Excellent work! Thanks very much.

**Comment by jsccast** [comment]
I'll merge it now. As you suggested, we should probably start using proper versioning soon.

**Pull request merged**
