### PR TITLE
feat(storage): added cassandra scan error handling and retry policy

### PR DESCRIPTION
**Pull request by decibelcooper**
This MR adds a tiny bit of much-needed improvements to the way errors reaching cassandra hosts are handled.

# Goals
* propagate errors in scanning cassandra database
* add exponential backoff retry policy to cassandra
* add configurable timeout to cassandra

### CODE REVIEW

**Comment by decibelcooper** [comment]
@jsccast I put a WIP flag in the description while I did some stress testing.  That is now complete, and things appear to be good.

**Comment by jsccast** [comment]
Thanks very much. Sorry for the premature merge!

**Comment by decibelcooper** [comment]
> Thanks very much. Sorry for the premature merge!

No problem, thank you for continuing to maintain this project.  Please let me know if there is any way I can make the process smoother since I will almost definitely have more contributions to make.

For future reference, I would prefer if my WIPs aren't merged, because it may just be for visibility and I might not have any confidence in the code at the point.

**Comment by jsccast** [comment]
Understood re WIP PRs!

Your contributions have been great. Happy to do what I can to see they get prompt attention.

**Pull request merged**
