### PR TITLE
Add option for 'or' operations to short circuit

### PR DESCRIPTION
**Pull request by raidancampbell**
Fairly self-explanatory.  There's some room for improvement in the marshaling, but it would increase the scope of the MR more than I was looking for.

### CODE REVIEW

**Comment by raidancampbell** [comment]
Travis failed due to an unexpected os.Exit(0) in the `github.com/Comcast/rulio/service` package: unfortunately I'm unable to replicate this locally.  Is there any chance this could be CI instability?

**Review by jsccast — CHANGES_REQUESTED** [review]
Nice! Thanks.

Do you mind making a quick addition to `doc/Manual.md` that describes this feature? I know the manual is -- well -- terse, but a mention of `shortCircuit` would be helpful.

**Comment by raidancampbell** [comment]
Added `a71823d32e717f84a48dd1811d472f208f00a898` to help document it

**Comment by raidancampbell** [comment]
> Travis failed due to an unexpected os.Exit(0) in the `github.com/Comcast/rulio/service` package: unfortunately I'm unable to replicate this locally. Is there any chance this could be CI instability?

Oh good, the Travis pipeline passed after the documentation update.  I'm gonna chalk up the first failure to instability

**Review by jsccast — APPROVED** [review]
Thanks again!

**Pull request merged**
